use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'ZDFoundation_Example' do
  pod 'ZDFoundation', :path => '../'

  target 'ZDFoundation_Tests' do
    inherit! :search_paths

    
  end
end
